#!/usr/bin/python3

import amulet

d = amulet.Deployment(series='trusty')

d.add('beaver')
d.expose('beaver')

try:
    d.setup(timeout=900)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

unit = d.sentry.unit['beaver/0']

# output, code = unit.run("ps -a | sed -n /beaver/p")
# if (code != 0):
#     amulet.raise_status(amulet.FAIL, msg="Failed to find beaver")
#     print(output)
# else:
#     print(output)
